name: Create release
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Read VERSION file
      id: getversion
      run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
    - name: Print Version number
      run: echo "Building version ${{ steps.getversion.outputs.version }}"
    - name: Zip Folder
      run: zip -r ${{ github.event.repository.name }}.v${{ steps.getversion.outputs.version }}.zip .
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.repository.name }}.v${{ steps.getversion.outputs.version }}.zip"
        body: "Release v${{ steps.getversion.outputs.version }} of OZR Singple Player Tarkov Mods - Please use just ${{ github.event.repository.name }}.v${{ steps.getversion.outputs.version }}.0.zip"
        tag: "v${{ steps.getversion.outputs.version }}"
        artifactErrorsFailBuild: true
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '{{ EVENT_PAYLOAD.repository.full_name }} - v${{ steps.getversion.outputs.version }} has been built and pushed'