name: Create release
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:   
    - name: Print new build number
      run: echo "Build number is ${{ github.run_number }}"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Zip Folder
      run: zip -r ${{ github.event.repository.name }}.${{ github.run_number }}.zip .
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.repository.name }}.${{ github.run_number }}.zip"
        body: "Release v${{ github.run_number }}"
        tag: "v${{ github.run_number }}"
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '{{ EVENT_PAYLOAD.repository.full_name }} - version ${{ github.run_number }} has been built and pushed'