name: Create release
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:   
    - name: Print new build number
      run: echo "Build number is ${{ github.run_number }}"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Zip Folder
      run: zip -r ${{ github.event.repository.name }}.${{ github.run_number }}.zip .
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.event.repository.name }}.${{ github.run_number }}.zip
      env:
        GITHUB_TOKEN: ${{secrets.github_token}}
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '{{ EVENT_PAYLOAD.repository.full_name }} - version ${{ github.run_number }} has been built and pushed'